# config/endpoints.yaml
token_info: "/core/v3/info"
employees_list: "/core/v3/employees"

# Work Entries
work_entries_list: "/schedule/v1/work-entries"
work_entries_create: "/schedule/v1/work-entries"
work_entries_update: "/schedule/v1/work-entries/{id}"
work_entries_delete: "/schedule/v1/work-entries/{id}"
work_entries_clock_in: "/schedule/v1/work-entries/clock-in"
work_entries_clock_out: "/schedule/v1/work-entries/clock-out"

# Time Entries
time_entries_list: "/project/v1/time-entries"

# Hours bag rule history
hours_bag_rule_history_list: "/schedule/v1/hours-bag-rule-history"

# Employee–Office assignations
employee_office_assignations_list: "/core/v3/employee-office-assignations"

# NEW: Offices
offices_list: "/core/v3/offices"
