# config/endpoints.yaml
sesame:
  token_info: "/core/v3/info"
  employees_list: "/core/v3/employees"
  employees_create: "/core/v3/employees"

  # ---- TIME / WORK ENTRIES ----
  time_entries_list: "/project/v1/time-entries"

  work_entries_list: "/schedule/v1/work-entries"
  work_entries_create: "/schedule/v1/work-entries"
  work_entries_update: "/schedule/v1/work-entries/{id}"
  work_entries_delete: "/schedule/v1/work-entries/{id}"

  # Acciones rápidas (fichar)
  work_entries_clock_in: "/schedule/v1/work-entries/clock-in"
  work_entries_clock_out: "/schedule/v1/work-entries/clock-out"

  # ---- HOURS BAG (bolsa de horas) ----
  hours_bag_rule_history_list: "/schedule/v1/hours-bag-rule-history"
